#!/bin/bash

export FLASK_APP=flask_main.py
SECRETS="secrets.txt"

if [ -s ${SECRETS} ]; then
    export FLASK_SECRET_KEY=$(cat secrets.txt)
else
    unset FLASK_SECRET_KEY
fi

if [ -z "$1" ]; then
    flask run
else
    flask $@
fi
