#!/bin/bash

export FLASK_APP=flask_main.py
export FLASK_ENV=development

SECRETS="secrets.txt"

if [ -s ${SECRETS} ]; then
    export FLASK_SECRET_KEY=$(cat secrets.txt)
else
    unset FLASK_SECRET_KEY
fi

if [ -z "$1" ]; then
    python3 flask_main.py
else
    flask "$@"
fi
