"""empty message

Revision ID: 329b3302d538
Revises: fff7fd76340b
Create Date: 2019-04-10 20:13:45.062537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329b3302d538'
down_revision = 'fff7fd76340b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_data', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('time', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
