"""empty message

Revision ID: 539a721225d9
Revises: 87d3c4d040a6
Create Date: 2019-04-08 20:14:49.203311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539a721225d9'
down_revision = '87d3c4d040a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sensor_data_sensor_name', table_name='sensor_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sensor_data_sensor_name', 'sensor_data', ['sensor_name'], unique=1)
    # ### end Alembic commands ###
