"""empty message

Revision ID: 87d3c4d040a6
Revises: d3ff1d422d1d
Create Date: 2019-04-08 20:09:06.252497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d3c4d040a6'
down_revision = 'd3ff1d422d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_name', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_data_sensor_name'), 'sensor_data', ['sensor_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_data_sensor_name'), table_name='sensor_data')
    op.drop_table('sensor_data')
    # ### end Alembic commands ###
