"""empty message

Revision ID: fff7fd76340b
Revises: 539a721225d9
Create Date: 2019-04-10 19:59:48.945105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff7fd76340b'
down_revision = '539a721225d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_data', 'date')
    # ### end Alembic commands ###
